# Generated by Django 6.0.2 on 2026-02-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='subproduct',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubProduct',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
