# Generated by Django 6.0.2 on 2026-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0004_remove_subproduct_product_remove_wishlist_subproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health_records', models.TextField()),
                ('milk_per_day', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead')], max_length=10)),
            ],
        ),
    ]
