# Generated by Django 6.0.2 on 2026-02-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_milk', models.FloatField()),
                ('evening_milk', models.FloatField()),
                ('total_milk', models.FloatField(blank=True, null=True)),
                ('milk_home', models.FloatField(default=0)),
                ('milk_sold', models.FloatField(default=0)),
                ('milk_wasted', models.FloatField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussiness.animal')),
            ],
        ),
    ]
