# Generated by Django 6.0.2 on 2026-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0006_milkrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.FloatField()),
                ('price_per_liter', models.FloatField()),
                ('total_income', models.FloatField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_received', models.BooleanField(default=False)),
            ],
        ),
    ]
