# Generated by Django 6.0.2 on 2026-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0007_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('veterinary', 'Veterinary'), ('medicines', 'Medicines'), ('labor', 'Labor'), ('electricity', 'Electricity'), ('water', 'Water'), ('equipment', 'Equipment'), ('animal_purchase', 'Animal Purchase'), ('maintenance', 'Maintenance')], max_length=50)),
                ('amount', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
